Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.provision "shell", path: "provision.sh"
	web.vm.provision "shell", inline: "apt-get install -y mysql-client"
    web.vm.network "private_network", ip: "192.168.50.4"
  end

  config.vm.define "db" do |db|
    db.vm.provision "shell", path: "db.provision.sh"
	db.vm.network "private_network", ip: "192.168.50.5"
  end
end